branches:
  only:
    - master
    - /^v.*$/

language: go

go:
  - "1.11"

env:
  - GO111MODULE=on

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

matrix:
  include:
    - name: Linux x86_64
      os: linux
      before_install:
        - sudo apt-get install libopenal-dev xorg-dev -y --allow-unauthenticated
      script:
        - go get -v ./...
        - go test -v -race ./...
        - go vet ./...
        - megacheck ./...
        - gocyclo -over 19 $GO_FILES
        - golint -set_exit_status $(go list ./...)
        - go build -v
      before_deploy:
        - if [[ -n "$TRAVIS_TAG" ]]; then OS="Linux" ARCH=x86_64 VERSION=${TRAVIS_TAG:1} make tar; fi
    - name: Linux arm
      os: linux
      before_install:
        - sudo apt-get install binutils-multiarch
        - sudo dpkg --add-architecture armhf
        - sudo echo "" > /etc/apt/sources.list
        - sudo echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" >> /etc/apt/sources.list
        - sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports trusty main restricted universe multiverse" >> /etc/apt/sources.list
        - sudo echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse" >> /etc/apt/sources.list
        - sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports trusty-updates main restricted universe multiverse" >> /etc/apt/sources.list
        - sudo echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list
        - sudo echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list
        - sudo apt-get update -q
        - sudo apt-get install gcc-arm-linux-gnueabihf libopenal-dev:armhf libgl1-mesa-dev:armhf libxcursor-dev:armhf libxrandr-dev:armhf libxinerama-dev:armhf libxi-dev:armhf -y --allow-unauthenticated
      script:
        - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go get -t -v ./...
        #- GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go test -v -race ./...
        - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go vet ./...
        - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc megacheck ./...
        - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc gocyclo -over 19 $GO_FILES
        - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc golint -set_exit_status $(go list ./...)
        - GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc go build -v
      before_deploy:
        - if [[ -n "$TRAVIS_TAG" ]]; then OS="Linux" ARCH=arm VERSION=${TRAVIS_TAG:1} make tar; fi
    - name: OSX
      os: osx
      before_install:
        - brew update
        - brew install openal-soft
      script:
        - go get -v ./...
        - go test -v -race ./...
        - go vet ./...
        - megacheck ./...
        - gocyclo -over 19 $GO_FILES
        - golint -set_exit_status $(go list ./...)
        - go build -v
      before_deploy:
        - if [[ -n "$TRAVIS_TAG" ]]; then OS="OSX" ARCH=x86_64 VERSION=${TRAVIS_TAG:1} make dmg; fi
    - name: Windows
      os: windows
      before_install:
        - ls -la "/c/Program Files"
        - ls -la "/c/Program Files (x86)"
        - choco install make
        - choco install vcredist140
        - wget http://static.kivutar.me/openal-soft-1.19.0-bin.zip
        - 7z x openal-soft-1.19.0-bin.zip -o/c/Users/travis/openal-soft-1.19.0-bin
        - export CGO_CFLAGS="-I/c/Users/travis/openal-soft-1.19.0-bin/include/"
        - export CGO_LDFLAGS="-L/c/Users/travis/openal-soft-1.19.0-bin/build/Release/"
      script:
        - go get -v ./...
        - go test -v ./...
        #- go vet ./...
        - megacheck ./...
        - gocyclo -over 19 $GO_FILES
        - golint -set_exit_status $(go list ./...)
        - go build -v
      before_deploy:
        - if [[ -n "$TRAVIS_TAG" ]]; then mkdir -p ./Ludo-Windows-x86_64-${TRAVIS_TAG:1}/; fi
        - if [[ -n "$TRAVIS_TAG" ]]; then cp /c/Users/travis/openal-soft-1.19.0-bin/build/Release/OpenAL32.* ./Ludo-Windows-x86_64-${TRAVIS_TAG:1}/; fi
        - if [[ -n "$TRAVIS_TAG" ]]; then OS="Windows" ARCH=x86_64 VERSION=${TRAVIS_TAG:1} make zip; fi

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: N/AOf4iKJoFBJ7NP6hWOHQHNyOj5A5B2WhHzh1pO5pQrLqSJumfTSZZiD5WX3m5ycLokI49xUqwQN7yyNpE8h5FOfjKn5h6Uq2VByTVCzfHgRXn/RbrGUBMnLbEwwVOlpbCv/tYybpqUzGOSkKkzDhbAjQugSbI8B9szHPyX0FnAPoOQzLQoPkHjyl9nHtFgc3gbgZUGEouo5mGmET0VuszbAFiW6UUHgCBGiciZa1TQHREHlM6cFjC+Z9MeqXAxfVCu3CCqxSFwQwGGFe3gfe12wu8LrOGD7FEp11vswKW1bePU1tOgTBC207TyBni9TXAYjpvuEgm1N5NnNsiR+IrggOrJczglvAgwLHPN5a8Tu8ZZsCEc1GotqGNBBFE1GZuhJ45NLvXw4VzCmqT9ciaUYFyl1G1hY8N8TiHWIT+wmklYzHMtHPqQhyzSHnAgnaY50B6vKNp835F3U+Rt9r0M5kgOARe2KeaVgUPxWWevav84cQLSj23yQU2zxNg+H6sOJ2yHS0S0m6e5UGj+Du/9kxICD7t0bEnC0KmD3BLGaR29aQfQxd8PPB2KEjitsQ9wPlzbIyh6I19yxzMBSIy6LDChcJNIDeL0v3fBkdSnOyh6RE+VENMNtVk+QndQWw0NkSuNYGMcGf31OYed6gJ1DZIXDX/vk0uGv7WXLaA=
  file:
    - Ludo-Linux-x86_64-${TRAVIS_TAG:1}.tar.gz
    - Ludo-Linux-arm-${TRAVIS_TAG:1}.tar.gz
    - Ludo-OSX-x86_64-${TRAVIS_TAG:1}.dmg
    - Ludo-Windows-x86_64-${TRAVIS_TAG:1}.zip
  on:
    repo: libretro/ludo
    tags: true

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
