branches:
  only:
    - master

language: go

go:
  - "1.9"

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:keithw/glfw3 -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libglfw3-dev libopenal-dev xorg-dev -y --allow-unauthenticated; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glfw openal-soft; fi

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - go get -t -v ./...
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then OS="Linux" VERSION=$TRAVIS_TAG make tar; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS="OSX" VERSION=$TRAVIS_TAG make dmg; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then OS="Windows" VERSION=$TRAVIS_TAG make zip; fi

deploy:
  provider: releases
  api_key:
    secure: N/AOf4iKJoFBJ7NP6hWOHQHNyOj5A5B2WhHzh1pO5pQrLqSJumfTSZZiD5WX3m5ycLokI49xUqwQN7yyNpE8h5FOfjKn5h6Uq2VByTVCzfHgRXn/RbrGUBMnLbEwwVOlpbCv/tYybpqUzGOSkKkzDhbAjQugSbI8B9szHPyX0FnAPoOQzLQoPkHjyl9nHtFgc3gbgZUGEouo5mGmET0VuszbAFiW6UUHgCBGiciZa1TQHREHlM6cFjC+Z9MeqXAxfVCu3CCqxSFwQwGGFe3gfe12wu8LrOGD7FEp11vswKW1bePU1tOgTBC207TyBni9TXAYjpvuEgm1N5NnNsiR+IrggOrJczglvAgwLHPN5a8Tu8ZZsCEc1GotqGNBBFE1GZuhJ45NLvXw4VzCmqT9ciaUYFyl1G1hY8N8TiHWIT+wmklYzHMtHPqQhyzSHnAgnaY50B6vKNp835F3U+Rt9r0M5kgOARe2KeaVgUPxWWevav84cQLSj23yQU2zxNg+H6sOJ2yHS0S0m6e5UGj+Du/9kxICD7t0bEnC0KmD3BLGaR29aQfQxd8PPB2KEjitsQ9wPlzbIyh6I19yxzMBSIy6LDChcJNIDeL0v3fBkdSnOyh6RE+VENMNtVk+QndQWw0NkSuNYGMcGf31OYed6gJ1DZIXDX/vk0uGv7WXLaA=
  file:
    - Ludo-*.tar.gz
    - Ludo-*.dmg
    - Ludo-*.zip
  on:
    tags: true
